---
- name: Check if playbook has been run before.
  stat:
    path: /etc/awx_playbook_complete
  register: awx_playbook_already_run

- name: Get path
  command: echo $PATH
  register: pathresult
- debug: var=pathresult

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ postgres_data_dir }}"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: false

- name: Pause for 30 seconds to permit awx_task to start
  pause:
    seconds: 30
  when: not awx_playbook_already_run.stat.exists

- name: Restart container service
  service:
    name: docker
    state: restarted
  when: not awx_playbook_already_run.stat.exists
