---
- name: Converge
  hosts: all
  become: true

  vars:
    nodejs_version: "10.x"
    nodejs_install_npm_user: root
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
