---
- name: Converge
  hosts: all
  become: true

  vars:
    nodejs_version: "10.x"
    nodejs_install_npm_user: root
    ansible_install_method: "pip"
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Update $PATH.
      lineinfile:
        path: /etc/environment
        line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/npm/bin"'
        insertafter: EOF
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - geerlingguy.pip
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.nodejs
    - geerlingguy.awx
